# Specify the cross-compiling toolchain
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR xtensa)


# Specify the cross compiler
set(XTENSA_ESP32_TOOLCHAIN_DIR ${PROJECT_SOURCE_DIR}/Toolchain/${DEVICE}/bin)
set(TOOLCHAIN_PREFIX xtensa-esp32-elf-)

set(CMAKE_C_COMPILER ${XTENSA_ESP32_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${XTENSA_ESP32_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER ${XTENSA_ESP32_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}ld)

set(CMAKE_OBJCOPY ${XTENSA_ESP32_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${XTENSA_ESP32_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_MAKE_PROGRAM "make" CACHE STRING "Make program")